### ISSUE TITLE
Error when inserting object when class implements interface

### ISSUE THREAD

**Issue by guyilin-amazon** [amzn/ion-object-mapper-dotnet#51]
The error `System.InvalidOperationException: This operation is only valid on generic types` occurs whenever we try to insert an object which implements interfaces. Example:
```c#
interface IInterface
{
    
}
class Car: IInterface
{
    public string Make { get; set; }  
    public string Model { get; set; }
    public int Year { get; set; }
}
```
The exception may come from the `GetGenericTypeDefinition()` API call in https://github.com/amzn/ion-object-mapper-dotnet/blob/554acb588c52fff0014b8034c43fc96b99867f5b/Amazon.IonObjectMapper/IonSerializer.cs#L185 without checking the type is generic type first, see https://docs.microsoft.com/en-us/dotnet/api/System.Type.GetGenericTypeDefinition?view=netcore-3.1#exceptions

**Comment by Lipe1994** [comment]
you have verify if interface is generic, using property IsGenericType, your interface is not generic...

`
Type genericDictionaryType = item
    .GetType()
    .GetInterfaces()
    .FirstOrDefault( t => t.IsGenericType && typeof(IDictionary<,>).IsAssignableFrom(t.GetGenericTypeDefinition()) );
`
