### ISSUE TITLE
Old version of Amazon.IonDotnet referenced

### ISSUE THREAD

**Issue by aalbin** [amzn/ion-object-mapper-dotnet#79]
An old version of `Amazon.IonDotnet` is referenced in the `Amazon.IonObjectMapper.csproj` file. This causes issues when implementing the IIonSerializer because the nuget package references version 1.2.2.

This is the code I am trying to write:

```
    public class EnumSerializerAsInt<T>
        : IIonSerializer
        where T : System.Enum
    {
        void Serialize(IIonWriter writer, object item)
        {
            writer.WriteInt((int)item);
        }

        object Deserialize(IIonReader reader)
        {
            var valueObject = Enum
                .ToObject(typeof(T), reader.IntValue());
            return valueObject;
        }
    }

    public class EnumSerializerAsString<T>
        : IIonSerializer
        where T : System.Enum
    {
        void Serialize(IIonWriter writer, object item)
        {
            writer.WriteString(item.ToString());
        }

        object Deserialize(IIonReader reader)
        {
            if (!Enum.TryParse(typeof(T), reader.StringValue(), out object valueObject))
                throw new Exception($"Unable to parse string value into {typeof(T).Name}: {reader.StringValue()}");

            return valueObject;
        }
    }
```

And the error I get is `The type 'IIonWriter' is defined in an assembly that is not referenced. You must add a reference to assembly 'Amazon.IonDotnet, Version=1.1.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. (CS0012) ([Project name redacted])`

But I believe the solution should be to update the reference to IonDotNet from version 1.1.0 to 1.2.2 in this file:

https://github.com/amzn/ion-object-mapper-dotnet/blob/ebe57142801d3992993f13ac5e4193ac3d350784/Amazon.IonObjectMapper/Amazon.IonObjectMapper.csproj#L21

**Comment by Aracron** [comment]
I am getting this exact same error, and am having to do down convert the ion object to json and then use jsonserializer.  This is extremely frustrating!
